require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 3
# Beacuse Rspec blocks inevitably violate block length
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
    - 'lib/tasks/*'
Layout/LineLength:
  Exclude:
    - 'config/initializers/*'
Rails/HasManyOrHasOneDependent: 
  Enabled: false
RSpec/FactoryBot/SyntaxMethods:
  Enabled: false